import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/footer";
import NavBar from "@/components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <NavBar />
            <main className="flex flex-1 mt-16 mb-8">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
